project:
  type: website
  output-dir: docs
website:
  title: "Andre Barbato"
  favicon: "images/favicon.png"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Projetos"
        file: projetos.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: github
        href: https://github.com/andrebarbato
      - icon: linkedin
        href: https://www.linkedin.com/in/andrebarbato/
  search: true
format:
  html:
    theme:
      light: flatly
      dark: [flatly,theme_dark_custom.scss]
    css: styles.css
    code-link: true
    code-tools: false
    code-fold: show
    highlight-style: github

editor: visual

