project:
  type: default
  output-dir: docs
website:
  title: "Andre Barbato"
  favicon: "images/favicon.png"
  sidebar:
    style: docked
    logo: "images/favicon.png"
    background: dark
    pinned: true
    contents:
      - about.qmd
  page-footer:
    center: "Copyright 2023, Andre Barbato"
    border: false
    right:
      - icon: github
        href: https://github.com/andrebarbato
      - icon: linkedin
        href: https://www.linkedin.com/in/andrebarbato/
  search: false 
format:
  html:
    theme:
      light: [darkly,theme_dark_custom.scss]
      dark: darkly
    css: styles.css
    code-link: true
    highlight-style: github

editor: visual

