project:
  type: website
  output-dir: docs
website:
  title: "Andre Barbato"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/andrebarbato
      - icon: linkedin
        href: https://www.linkedin.com/in/andrebarbato/
format:
  html:
    theme: 
      light: sandstone
      dark: darkly
    css: styles.css
    highlight-style: zenburn

editor: visual

